### ISSUE TITLE
Is there any demo code for vue3 with typescript run in browser?

### ISSUE THREAD

**Issue by cathino** [hackape/talib.js#1] opened 2021-11-09 06:16 UTC
Could you provide a simple full demo code?I mean the code include "import" statement.

Thank you.

**Comment by hackape** [comment] 2021-11-10 04:54
Not sure how vue3 is related. I'mma just show you a TS example.

```ts
import { init, ADD } from "talib.js";

async function main() {
  // remember to call init at least once.
  await init(/* optionally pass in .wasm file path here */);

  // usage:
  const inReal = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
  console.log("talib.ADD result:", ADD({ inReal0: inReal, inReal1: inReal }));
}

main();
```

**Comment by cathino** [comment] 2021-11-12 06:39
@hackape I tried the code you given, it shows:

```
index.esm.js?80e5:561 
        
       Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (webpack-internal:///./node_modules/talib.js/lib/index.esm.js:886)
    at eval (webpack-internal:///./node_modules/talib.js/lib/index.esm.js:962)
index.esm.js?80e5:2146 
        
       Uncaught (in promise) Error: TA-Lib WASM runtime init fail.
Error: 
abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info.
    at eval (webpack-internal:///./node_modules/talib.js/lib/index.esm.js:2471)
```

**Comment by hackape** [comment] 2021-11-12 10:17
The issue is webpack related. I’m sorry I cannot address bundler problem, it’s out of scope. 

For now I can only suggest a workaround. The idea is to supply the URL to the `.wasm` file as argument to `init()` function. 

```js
await init("https://unpkg.com/talib.js@0.1.0/lib/talib.wasm");
```

You can host this file yourself if you like. It’s just a static asset, like a picture, nothing magical. 

If you decide to host it, 2 things to check:
1. Make sure the URL is accessible from your origin, e.g. double check CORS config if involved. 
2. Make sure the MIME type is correctly set to `application/wasm`.

**Comment by cathino** [comment] 2021-11-15 01:37
@hackape It works,thank yuou

**Closed as completed** 2021-11-15 01:37 UTC

**Comment by deviceGT** [comment] 2021-11-15 03:53
I found it,there should be an options with mimetype: "application/wasm",the vue.config.js file like:

```js
module.exports = {
    chainWebpack: (webpackConfig) => {
        webpackConfig.module
            .rule("wasm")
            .test(/.wasm$/)
            .use("wasm-loader")
            .loader("wasm-loader")
            .options({
                mimetype: "application/wasm",
            });
    },
};
```

After that,I can init with a local **.wasm** file.

That's a good way to use wasm with webpack and  vue3.

**Comment by deviceGT** [comment] 2021-11-16 12:49
Because I dont't know the way to using webpack package wasm file,I have two ways

#### For develop:

```js
await init("https://unpkg.com/talib.js@0.1.0/lib/talib.wasm");
```

#### For release:

```js
await init();
```

It's import to copy `node_modules/talib.js/lib/talib.wasm` to `/js` dir of your web site

<<<END

If who knows howto package wasm with webpack,tell me please
